server:
  port: 80

# 开启api里的fallbackFactory，用于hystrix服务降级
feign:
  hystrix:
    enabled: true

# 告诉80，不能直接去找8001，需要去eureka获取注册的8001
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/